dist: xenial
os: linux
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
jobs:
  include:
    - stage: release
      node_js: lts/*
      before_deploy:
        - npm run build
      deploy:
        provider: script
        cleanup: false
        script:
          - npx semantic-release
